### PR TITLE
Fix bundler dependency

### PR DESCRIPTION
**Pull request by bliof**
.. it is a runtime dependencies because we parse Gemfiles with it ..

On 0.3.0 when you do `gem install hellgrid` and run `hellgrid` you'll
get an error:

```
$ hellgrid
Could not find diff-lcs-1.2.5 in any of the sources
Run `bundle install` to install missing gems.
```

### CODE REVIEW

**Comment by bliof** [comment]
To test

```
gem build hellgrid.gemspec
gem install hellgrid-0.3.1.gem
cd .. && hellgrid
```

**Comment by damien** [comment]
This _is_ weird. One thing that catches my attention is a line that isn't actually from this PR: https://github.com/FundingCircle/hellgrid/blob/fix-dependencies/bin/hellgrid#L4

That seems incorrect to me. One way you could verify this in your CI build is to have it output `$LOAD_PATH` so you can see where ruby/bundler is searching for dependencies.

What I _suspect_ is happening, since this application doesn't seem to have it's own dependencies on diff-lcs, is that Bundler is unable to find _it's_ own dependencies because the load path is misconfigured. This would also explain why things don't blow up until you explicitly call `Bundle.require`.

**Comment by bliof** [comment]
@damien the `ENV['BUNDLE_GEMFILE'] ||= ..` is a "hack". The gem uses `bundler` to parse `Gemfile.lock` files and the bundler gem expects a `Gemfile` or a `.bundle` to even start :) So.. this thing makes sure that the command will work even if there isn't a `Gemfile` up the directory tree. 

I'll try to remove the `bundler/setup` 🤷‍♂️

**Comment by bliof** [comment]
@damien 👀 Done ✅

**Comment by bliof** [comment]
@dobrinov 👓 🍻

**Review by damien — APPROVED** [review]

**Pull request merged**
